#!/bin/bash

system_wide_filelist=''
user_filelist=''

if [ -r /etc/cdg_paths ]; then
   system_wide_filelist=$(cdscuts_list_echo /etc/cdg_paths)
fi
if [ -r ~/.cdg_paths ]; then
   user_filelist=$(cdscuts_list_echo ~/.cdg_paths)
fi

echo -e "$system_wide_filelist\n$user_filelist" | sed '/^\s*$/d'
