complete -c dotfiles -f
complete -c dotfiles -n "__fish_use_subcommand" -a "edit" -d "Edit managed file"
complete -c dotfiles -n "__fish_use_subcommand" -a "diff" -d "Show pending changes"
complete -c dotfiles -n "__fish_use_subcommand" -a "sync" -d "Apply all changes"
complete -c dotfiles -n "__fish_use_subcommand" -a "status" -d "Show status"
complete -c dotfiles -n "__fish_use_subcommand" -a "cd" -d "Go to source dir"
complete -c dotfiles -n "__fish_use_subcommand" -a "refresh" -d "Re-download externals"
complete -c dotfiles -n "__fish_use_subcommand" -a "add" -d "Add file to chezmoi"
complete -c dotfiles -n "__fish_use_subcommand" -a "update" -d "Pull latest + apply"
complete -c dotfiles -n "__fish_use_subcommand" -a "doctor" -d "Health check"
complete -c dotfiles -n "__fish_use_subcommand" -a "bench" -d "Benchmark shell startup"
complete -c dotfiles -n "__fish_use_subcommand" -a "encrypt-setup" -d "Set up age encryption"
