site_name: OmniSharpSublime
theme: readthedocs
repo_url: https://github.com/OmniSharp/omnisharp-sublime 
pages:
- [index.md, Home]
- [buildsystems.md, Build Systems]
- [filetemplates.md, File Templates]
